services:
  _defaults:
    autowire: true
    autoconfigure: true
  CJDevStudios\AppConfigBundle\:
    resource: '../src/*'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Tests/'
